### ISSUE TITLE
Inconsistent metrics reported during and after training

### ISSUE THREAD

**Issue by jeremyadamsfisher** [GLambard/SMILES-X#8]
Validation metrics look much better while training. From the `SMILESX_Prediction_github.ipynb` notebook:
```
273/273 [==============================] - 2s 8ms/step - loss: 0.0013 - mean_absolute_error: 0.0277 - mean_squared_error: 0.0013 - val_loss: 0.0101 - val_mean_absolute_error: 0.0625 - val_mean_squared_error: 0.0101
Best val_loss @ Epoch #37

***Predictions from the best model.***

For the training set:
MAE: 0.4164 RMSE: 0.5672 R^2: 0.9799

For the validation set:
MAE: 0.5921 RMSE: 0.8804 R^2: 0.9324

For the test set:
MAE: 0.4668 RMSE: 0.7007 R^2: 0.9350
```
Final predictions gives `MAE: 0.5921` whereas the prediction during training gives ` val_mean_absolute_error: 0.0625`. I would put more trust in the "Predictions from the best model" because its averaging the result of augmented smiles. Is this the correct interpretation?

**Comment by egracheva** [comment]
@jeremyadamsfisher, thank you for your question and sorry for such a late response.

There is no issue here, since we use the data scaling: during the training the model internally evaluates all the errors based on the scaled data (and this is what it prints out).
The final errors are reported after the data has been unscaled back.
Therefore, you should rely on this last MAE of 0.5921.

**Comment by jeremyadamsfisher** [comment]
Got it, thanks for the clarification!
